jumlahhewan = int(input('Ketik total hewan?:'))
print(f'berapa total hewan{jumlahhewan}')
berapakaki = input('Ketik total kaki hewan?:')
print(f'berapa total kaki{berapakaki}')
kakia = input('Ketik jumlah kaki hewan A?:')
print(f'kaki A{kakia}')
kakib = input('Ketik jumlah kaki hewan B?:')
print(f'kaki B{kakib}')
hewanxy = input('hewan A = x, hewan B = y')
print(f'hewan A = x, hewan B = y')